dist: trusty
sudo: required
group: edge
language: node_js
node_js:
  - "7"
addons:
  chrome: stable
branches:
  only:
    - master
    - develop
git:
  depth: 3
notifications:
  email:
    recipients:
      - platform@veo-labs.com
    on_success: always
    on_failure: always
before_install:
  - rvm install ruby-latest
  - npm install -g grunt-cli
  - npm install -g flightplan
  - npm install -g bower
  - gem install sass
  - gem install compass
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
  - echo "deb http://repo.mongodb.org/apt/ubuntu precise/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list
  - sudo apt-get update
  - sudo apt-get install -y mongodb-org=3.2.14 mongodb-org-server=3.2.14 mongodb-org-shell=3.2.14 mongodb-org-mongos=3.2.14 mongodb-org-tools=3.2.14
  - sudo service mongod start
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
install:
  - npm install flightplan
  - npm install --ignore-scripts
  - bower install
  - grunt prod
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 15
  - mongo openveo-test --eval "db.createUser({user:'travis',pwd:'test',roles:['readWrite']})";
script:
  - fly unit:local
  - fly e2e:local --skipInstall
